package metadata

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/anchore/syft/syft"
	"github.com/anchore/syft/syft/format"
	"github.com/anchore/syft/syft/format/cyclonedxjson"
	"github.com/anchore/syft/syft/format/spdxjson"
	"github.com/anchore/syft/syft/sbom"
	_ "github.com/glebarez/go-sqlite"

	"github.com/broadsage/doko/internal/providers"
)

// GetCleanImageName parses an OCI image reference and returns a clean brand-prefixed lowercase name (e.g. "bhi-alpine").
func GetCleanImageName(imageRef string) string {
	if imageRef == "" {
		return "bhi-image"
	}
	parts := strings.Split(imageRef, "/")
	baseName := parts[len(parts)-1]
	if idx := strings.Index(baseName, ":"); idx != -1 {
		baseName = baseName[:idx]
	}
	if idx := strings.Index(baseName, "@"); idx != -1 {
		baseName = baseName[:idx]
	}
	return "bhi-" + strings.ToLower(baseName)
}

// GenerateSBOM scans a simulated package directory using Syft to generate an SBOM in the specified format (cyclonedx or spdx).
// It returns the generated bytes, the filename suffix (e.g. "sbom.cdx.json" or "sbom.spdx.json"), and any error encountered.
func GenerateSBOM(ctx context.Context, imageName string, resolvedPkgs []providers.Package, formatName string) ([]byte, string, error) {
	// Create a temporary directory to simulate the container filesystem
	tempDir, err := os.MkdirTemp("", "doko-sbom-*")
	if err != nil {
		return nil, "", fmt.Errorf("failed to create temp directory for SBOM: %w", err)
	}
	defer os.RemoveAll(tempDir)

	// Simulate Alpine package database: /lib/apk/db/installed
	apkDbDir := filepath.Join(tempDir, "lib", "apk", "db")
	if err := os.MkdirAll(apkDbDir, 0755); err != nil {
		return nil, "", fmt.Errorf("failed to create apk db dir: %w", err)
	}

	apkDbPath := filepath.Join(apkDbDir, "installed")
	f, err := os.OpenFile(apkDbPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644)
	if err != nil {
		return nil, "", fmt.Errorf("failed to create apk installed db: %w", err)
	}

	for _, p := range resolvedPkgs {
		// Construct the APK installed format entry
		entry := fmt.Sprintf("P:%s\nV:%s\nA:%s\nL:%s\nT:%s\nU:%s\nS:%d\n\n",
			p.Name,
			p.Version,
			p.Arch,
			p.License,
			p.Description,
			p.DownloadURL,
			p.Size,
		)
		if _, err := f.WriteString(entry); err != nil {
			f.Close()
			return nil, "", fmt.Errorf("failed to write apk database entry: %w", err)
		}
	}
	f.Close() // Close before scanning

	// Use Syft Go SDK to scan the simulated directory
	src, err := syft.GetSource(ctx, tempDir, nil)
	if err != nil {
		return nil, "", fmt.Errorf("failed to get source for Syft scan: %w", err)
	}

	sbomObj, err := syft.CreateSBOM(ctx, src, nil)
	if err != nil {
		return nil, "", fmt.Errorf("failed to generate SBOM: %w", err)
	}

	// Set the name of the source in the description
	sbomObj.Source.Name = imageName

	var encoder sbom.FormatEncoder
	var suffix string

	switch strings.ToLower(formatName) {
	case "spdx":
		cfg := spdxjson.DefaultEncoderConfig()
		encoder, err = spdxjson.NewFormatEncoderWithConfig(cfg)
		if err != nil {
			return nil, "", fmt.Errorf("failed to create SPDX encoder: %w", err)
		}
		suffix = "sbom.spdx.json"
	default:
		cfg := cyclonedxjson.DefaultEncoderConfig()
		encoder, err = cyclonedxjson.NewFormatEncoderWithConfig(cfg)
		if err != nil {
			return nil, "", fmt.Errorf("failed to create CycloneDX encoder: %w", err)
		}
		suffix = "sbom.cdx.json"
	}

	encodedBytes, err := format.Encode(*sbomObj, encoder)
	if err != nil {
		return nil, "", fmt.Errorf("failed to encode SBOM: %w", err)
	}

	return encodedBytes, suffix, nil
}
