name: Test Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-examples:
    name: test examples (${{ matrix.example }})
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        example: [nginx, postgres, python-api, redis, jq-from-source]

    steps:
      - uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: test ${{ matrix.example }} example
        run: go test ./examples/... -v -count=1 -run TestExampleConfigs/${{ matrix.example }}
